#!/bin/bash

usage() { 
    echo "Usage: $(basename $0) -r <root certificate> -i <intermediate certificate> -k <root key> -l <intermediate key> -f <fabric id> -n <node id>"
    echo ""
    echo "    Notes :"
    echo "    1. certificates and keys expected in PEM format"
    echo "    2. chip-cert tool shall be in the PATH"
    echo ""
    exit 1; 
}

while getopts ":r:i:k:l:n:f:" option; do
    case "${option}" in
        r)
            root=${OPTARG}
            ;;
        i)
            intermediate=${OPTARG}
            ;;
        k)
            rkey=${OPTARG}
            ;;
        l)
            ikey=${OPTARG}
            ;;
        n)
            node=${OPTARG}
            ;;
        f)
            fabric=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done

# Check arguments
[ -v root ] && [ -v intermediate ] && [ -v rkey ] && [ -v ikey ] && [ -v fabric ] && [ -v node ] || usage
command -v chip-cert || usage

# Compute node of fabric id as a little endian hex string
convertId() {
    convertedId=""
    val=0
    id=$1
    for i in {1..8}
    do
        val=$((id % 256))
        id=$((id >> 8))
        convertedId="${convertedId}$(printf %02X ${val})"
    done
    echo $convertedId
}

# Generate store.ini
echo "[Default]"
echo "ExampleCARootCert0=$(sed -e '/^-/d' ${root} | paste -sd '')"
echo "ExampleCAIntermediateCert0=$(sed -e '/^-/d' ${intermediate} | paste -sd '')"
echo "ExampleOpCredsCAKey0=$(chip-cert convert-key ${rkey}  -b -)"
echo "ExampleOpCredsICAKey0=$(chip-cert convert-key ${ikey}  -b -)"
echo "LocalNodeId=$(echo "0: $(convertId $node)" | xxd -r | base64)"
echo "FabricId=$(echo "0: $(convertId $fabric)" | xxd -r | base64)"
